### ISSUE TITLE
Help Please: ProxLB Reporting SSL Issue

### ISSUE THREAD

**Issue by Dulux-Oz** [gyptazy/ProxLB#122]
Hi All,

I'm getting a very cryptic (ie unhelpful) error message in the Journal:

```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)
```

That's it! Nothing else apart from various python errors/issues all stemming from the above.

Would really appreciate some guidance because my Proxmox Cluster is working AOK otherwise (including correctly with SSL/TLS).

Cheers
Dulux-Oz

PS Damn "automatic" label adder - how the hell do you change / add correct ones?

**Comment by Dulux-Oz** [comment]
Sorry, the issue was cause by an underlying issue which this brought to light.

The situation had nothing to do with ProxLB and has now been resolved.

This can now be closed as successfully resolved.

**Comment by gyptazy** [comment]
hey @Dulux-Oz,

> PS Damn "automatic" label adder - how the hell do you change / add correct ones?

Those ones are created automatically based on the selected issue (you selected feature instead of bug). Needs-validation is assigned to all new requests which allows me to filter issue where I need to have a look at.


> Sorry, the issue was cause by an underlying issue which this brought to light.
> 
> The situation had nothing to do with ProxLB and has now been resolved.

Happy to hear and thanks for the information and the update :)

Cheers
gyptazy
