### ISSUE TITLE
`Bug`: CPU balancing may not work correctly (gathering metrics of node)

### ISSUE THREAD

**Issue by gyptazy** [gyptazy/ProxLB#75]
## General
Gathering metrics of nodes for the type of CPU for a balancing based on the CPU usage may provide wrong output.

**Comment by gyptazy** [comment]
False positive bug. Works as expected, false positive.
closing; no fix required.

**Comment by glitchvern** [comment]
Find attached a patch to help with cpu balancing.
[cpu.diff.txt](https://github.com/user-attachments/files/17334002/cpu.diff.txt)
cpu_assigned and cpu_used seem backwards from how memory_assigned and memory_used are done.

cpu_free needs the used cpu multiplied by the maxcpu before being subtracted from the maxcpu.  I've also dropped the rounding for this calculation as it was doing funny things with a "small" number of cores, so this stat is now a float instead of an int.

Then I've added a section in balancing_vm_calculations to choose the next most used vm if the current most used vm is already on the node with the most free resources.  Checking that the number of processed VMs is less than the total number of VMs prevents an infinite loop.

I only tested this with method: cpu, mode_option: percent, and balanciness: 15.  I didn't test what these changes did to the memory method or the default mode_option.  I tested with a balanciness of 15 percent so VMs would eventually settle on a host and not just bounce back and forth.

This was tested in a three node lab made of some of our old spare server hardware.  Two nodes have 8 cpu cores (no hyper-threading) and the other node has 16 cores with hyper-threading so proxmox reports 32 cores.  The different node sizes generate some interesting corner cases.  This is a test cluster with ceph running with a layout of identical enterprise ssd drives on each node.  The cluster was tested using fio.  Some test runs were with fio using the cpuio ioengine to generate various cpuloads on various VMs with no disk tests putting any additional load on the ceph system.  Some test runs were with fio using the psync engine to load the ceph system with additional VMs using fio with the cpuio ioengine to create additional cpu load.  Generating a sufficient load on the ceph system correctly causes all the VMs to migrate to the larger node.

All testing was done with a static load on the VMs.  Real world VMs often have a shifting load.  It might be better to use the rrddata on both the nodes and the VMs to create a 15 minute cpu load average on the nodes and VMs instead of using the current instantaneous usage.  https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/rrddata and https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/rrddata respectively.  A timeframe=hour gives a bunch of results each with cpu, maxcpu, and time.  Taking the last 15 by time and averaging the cpu x maxcpu should produce a usable cpu_used stat.

**Comment by gyptazy** [comment]
Hey @glitchvern,

> Find attached a patch to help with cpu balancing. [cpu.diff.txt](https://github.com/user-attachments/files/17334002/cpu.diff.txt) cpu_assigned and cpu_used seem backwards from how memory_assigned and memory_used are done.

Thank you very much for putting the time and efforts into providing the patch! Really appreciated!

> cpu_free needs the used cpu multiplied by the maxcpu before being subtracted from the maxcpu. I've also dropped the rounding for this calculation as it was doing funny things with a "small" number of cores, so this stat is now a float instead of an int.

Oh, thanks for fixing this.

> I only tested this with method: cpu, mode_option: percent, and balanciness: 15. I didn't test what these changes did to the memory method or the default mode_option. I tested with a balanciness of 15 percent so VMs would eventually settle on a host and not just bounce back and forth.

Thanks for also testing this. I also just run my tests and it doesn't affect the memory or disk balancing. So, we might integrate this to the upcoming 1.0.4 release.

> All testing was done with a static load on the VMs. Real world VMs often have a shifting load. It might be better to use the rrddata on both the nodes and the VMs to create a 15 minute cpu load average on the nodes and VMs instead of using the current instantaneous usage. [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/rrddata](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/rrddata) and [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/rrddata](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/%7Bnode%7D/qemu/%7Bvmid%7D/rrddata) respectively. A timeframe=hour gives a bunch of results each with cpu, maxcpu, and time. Taking the last 15 by time and averaging the cpu x maxcpu should produce a usable cpu_used stat.

Thanks for the hints. When I created ProxLB it was basically only meant for memory balancing but it was more about taking the low hanging fruits to also integrate cpu and disk. While disk got also more important for things like storage DRS, I really missed to give cpu based things a real try. The idea of using the average values within a given time period instead of the current ones is a great idea. I created issue #94 for this and can clearly see the benefits for cpu based workloads where this is simply too volatile.

Thanks for your hints and the provided patch!

Cheers,
gyptazy
