### ISSUE TITLE
Feature: Putting hosts in to Maintenance Mode.

### ISSUE THREAD

**Issue by vizerei** [gyptazy/ProxLB#84]
Similar to VMWare, I would like to be able to put a cluster in "Maintenance Mode" ideally from the GUI but CLI is fine for now. This should function by removing it from consideration for any incoming VMs and immediately begin balancing out all of the existing VMs/CTs away as if the server/host is stuck at 100% usage. Needed for patching/HW Upgrades/Testing etc.

**Comment by gyptazy** [comment]
Hey @vizerei,

thanks for providing this idea!

Something like that is already on the roadmap and part of the rolling-update support. There's also already a PR (https://github.com/gyptazy/ProxLB/pull/48). However, it'll still take some time because it comes in addition with the ProxLB API. Maybe I can find some time and create a small release including an option to put a node into a maintenance mode.

Cheers,
gyptazy

**Comment by vizerei** [comment]
Yeah I saw that feature request. It kind of made sense to me that this would be a stepping stone on the way to that while also providing more general usefulness.

**Comment by gyptazy** [comment]
Duplicate to request #58

**Comment by gyptazy** [comment]
Hey @vizerei,

this feature is now included and can be tested from the `main` branch. You can find more about the usage in https://github.com/gyptazy/ProxLB/pull/87.

This feature will be part of the upcoming 1.0.4 release.

Cheers,
gyptazy

**Comment by vizerei** [comment]
You are the best!  Would be great to put this on a repo so that it can be added to sources and updated from the WebUI but I know you're one person.  Will test ASAP
